name: Build EA DLC Unlocker v2

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup MSVC
      uses: microsoft/setup-msbuild@v1.1
    
    - name: Download Microsoft Detours
      run: |
        curl -L -o detours.zip https://github.com/microsoft/Detours/archive/refs/tags/v4.0.1.zip
        Expand-Archive detours.zip -DestinationPath .
        Rename-Item Detours-4.0.1 Detours
      shell: powershell
    
    - name: Build Detours
      run: |
        cd Detours/src
        nmake
      shell: cmd
    
    - name: Build version.dll
      run: |
        cl.exe /LD version.cpp /DEF:version.def /EHsc ^
          /I"Detours/include" ^
          /link Detours/lib.X64/detours.lib kernel32.lib user32.lib shell32.lib wininet.lib version.lib
      shell: cmd
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: version-dll
        path: |
          version.dll
          version.lib
          version.exp