name: Build EA DLC Unlocker v2

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup MSVC
      uses: microsoft/setup-msbuild@v2
    
    - name: Setup Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
    
    - name: Download and Build Detours
      shell: powershell
      run: |
        Invoke-WebRequest -Uri "https://github.com/microsoft/Detours/archive/refs/tags/v4.0.1.zip" -OutFile "detours.zip"
        Expand-Archive -Path "detours.zip" -DestinationPath "."
        cd Detours-4.0.1/src
        nmake
        cd ../..
    
    - name: Compile DLL
      shell: cmd
      run: |
        cl.exe /LD version.cpp /DEF:version.def /EHsc /I"Detours-4.0.1/include" /link Detours-4.0.1/lib.X64/detours.lib kernel32.lib user32.lib shell32.lib wininet.lib version.lib
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: version-dll-x64
        path: |
          version.dll
          version.lib